import { Outfit } from "next/font/google";
import "./globals.css";
import LocaleWrapper from "../components/LocaleWrapper"; // new file we'll create

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "DH Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <LocaleWrapper>{children}</LocaleWrapper>
      </body>
    </html>
  );
}